<script lang="ts">
	import '../styles/index.css';
	import { onNavigate } from '$app/navigation';
	import { page } from '$app/state';
	import { trackAnalytics } from '../analytics/index.js';
	import { SITE_NAME, SITE_URL } from '#shared/lib/site.js';
	import { ModeWatcher } from 'mode-watcher';
	import { Toaster } from '#shared/ui/sonner/index.js';
	import { HoloDefs } from '#shared/ui/holo/index.js';
	import { SiteHeader } from '#widgets/siteHeader/index.js';
	import { SiteFooter } from '#widgets/siteFooter/index.js';

	let { children } = $props();

	trackAnalytics();

	// Page changes cross-fade through the View Transitions API where the browser has it; the
	// header and footer carry their own transition names, so only the page between them moves.
	// Same-page query updates (filters, the compare page's picks) are not navigations here.
	onNavigate((navigation) => {
		if (navigation.shallow) return;
		if (!document.startViewTransition) return;
		if (navigation.from?.url.pathname === navigation.to?.url.pathname) return;
		return new Promise((resolve) => {
			document.startViewTransition(async () => {
				resolve();
				await navigation.complete;
			});
		});
	});
</script>

<svelte:head>
	<!-- Generated by scripts/generate-icons.mjs into static/; the order is RealFaviconGenerator's. -->
	<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
	<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
	<link rel="shortcut icon" href="/favicon.ico" />
	<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
	<meta name="apple-mobile-web-app-title" content={SITE_NAME} />
	<link rel="manifest" href="/site.webmanifest" />
	<meta name="theme-color" content="#111016" />
	<meta property="og:locale" content="en_US" />
	<!-- The deployed address, not whatever host served this copy: previews and search results
	should always point at the real site. -->
	{#if !page.error}
		<link rel="canonical" href="{SITE_URL}{page.url.pathname}" />
	{/if}
	<meta property="og:site_name" content={SITE_NAME} />
	{#if !page.error}
		<meta property="og:url" content="{SITE_URL}{page.url.pathname}" />
	{/if}
</svelte:head>

<ModeWatcher defaultMode="dark" />
<Toaster position="bottom-center" />
<HoloDefs />

<div class="flex min-h-dvh flex-col">
	<SiteHeader />
	<main id="main" tabindex="-1" class="flex-1 outline-none">
		{@render children()}
	</main>
	<SiteFooter />
</div>
